### ISSUE TITLE
Django 1.7 compatibility issues

### ISSUE THREAD

**Issue by facconi** [mthornhill/django-postal#18]
Hi. I am trying to use Postal with Django 1.7, but I receive the following error:

ImportError: cannot import name simplejson

The issue is actually a django-piston one, but I think it would be better to django-postal not to depend on django-piston.

**Comment by facconi** [comment]
I have fixed the "import simplejson" issue in Pull Request #19 and I have added a few bunch features.
Is it possible for you to release a new version on PyPi?

Please note that my pull request does not close this issue because django-postal still depends on django-piston, and django-piston is still not compatible with Django>=1.7. I suggest to remove dependancy.

**Comment by codingjoe** [comment]
:+1:

**Comment by mthornhill** [comment]
Hi Francesco,
I will remove the django-piston dependency (or accept pull request) and release a new version next week , all going well.
Thanks
Michael

**Comment by mthornhill** [comment]
Hi Francesco,
I've uploaded a new version at https://pypi.python.org/pypi/django-postal/0.96
Thanks again for your contribution.
Michael
